# fly.toml app configuration file generated for webstore0 on 2023-12-11T16:37:39-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "webstore0"
primary_region = "iad"

[build]
  image = "nickfraser40/webstore:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"
  StripeSettings__PublishableKey="pk_test_51ODBo1FwlogWasXXCKia1zm8yAdXh8Qu8mxhfFpowbKs3nIpnbUHxSb5qeMIRtRgRaxpAlDKGPJBENx9wjUUBOiU00gv7xToPC"


[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
